package com.example.islami.ui.quran.model

data class QuranSurah(
    val number: Int,
    val englishName: String,
    val arabicName: String,
    val numberOfVerses: Int
) {
    companion object {
        val quranSurah = listOf(
            QuranSurah(1, "Al-Fatihah", "الفاتحة", 7),
            QuranSurah(2, "Al-Baqarah", "البقرة", 286),
            QuranSurah(3, "Aal-E-Imran", "آل عمران", 200),
            QuranSurah(4, "An-Nisa", "النساء", 176),
            QuranSurah(5, "Al-Ma'idah", "المائدة", 120),
            QuranSurah(6, "Al-An'am", "الأنعام", 165),
            QuranSurah(7, "Al-A'raf", "الأعراف", 206),
            QuranSurah(8, "Al-Anfal", "الأنفال", 75),
            QuranSurah(9, "At-Tawbah", "التوبة", 129),
            QuranSurah(10, "Yunus", "يونس", 109),
            QuranSurah(11, "Hud", "هود", 123),
            QuranSurah(12, "Yusuf", "يوسف", 111),
            QuranSurah(13, "Ar-Ra'd", "الرعد", 43),
            QuranSurah(14, "Ibrahim", "ابراهيم", 52),
            QuranSurah(15, "Al-Hijr", "الحجر", 99),
            QuranSurah(16, "An-Nahl", "النحل", 128),
            QuranSurah(17, "Al-Isra", "الإسراء", 111),
            QuranSurah(18, "Al-Kahf", "الكهف", 110),
            QuranSurah(19, "Maryam", "مريم", 98),
            QuranSurah(20, "Taha", "طه", 135),
            QuranSurah(21, "Al-Anbiya", "الأنبياء", 112),
            QuranSurah(22, "Al-Hajj", "الحج", 78),
            QuranSurah(23, "Al-Mu'minun", "المؤمنون", 118),
            QuranSurah(24, "An-Nur", "النور", 64),
            QuranSurah(25, "Al-Furqan", "الفرقان", 77),
            QuranSurah(26, "Ash-Shu'ara", "الشعراء", 227),
            QuranSurah(27, "An-Naml", "النمل", 93),
            QuranSurah(28, "Al-Qasas", "القصص", 88),
            QuranSurah(29, "Al-Ankabut", "العنكبوت", 69),
            QuranSurah(30, "Ar-Rum", "الروم", 60),
            QuranSurah(31, "Luqman", "لقمان", 34),
            QuranSurah(32, "As-Sajdah", "السجدة", 30),
            QuranSurah(33, "Al-Ahzab", "الأحزاب", 73),
            QuranSurah(34, "Saba", "سبإ", 54),
            QuranSurah(35, "Fatir", "فاطر", 45),
            QuranSurah(36, "Ya-Sin", "يس", 83),
            QuranSurah(37, "As-Saffat", "الصافات", 182),
            QuranSurah(38, "Sad", "ص", 88),
            QuranSurah(39, "Az-Zumar", "الزمر", 75),
            QuranSurah(40, "Ghafir", "غافر", 85),
            QuranSurah(41, "Fussilat", "فصلت", 54),
            QuranSurah(42, "Ash-Shura", "الشورى", 53),
            QuranSurah(43, "Az-Zukhruf", "الزخرف", 89),
            QuranSurah(44, "Ad-Dukhan", "الدخان", 59),
            QuranSurah(45, "Al-Jathiyah", "الجاثية", 37),
            QuranSurah(46, "Al-Ahqaf", "الأحقاف", 35),
            QuranSurah(47, "Muhammad", "محمد", 38),
            QuranSurah(48, "Al-Fath", "الفتح", 29),
            QuranSurah(49, "Al-Hujurat", "الحجرات", 18),
            QuranSurah(50, "Qaf", "ق", 45),
            QuranSurah(51, "Adh-Dhariyat", "الذاريات", 60),
            QuranSurah(52, "At-Tur", "الطور", 49),
            QuranSurah(53, "An-Najm", "النجم", 62),
            QuranSurah(54, "Al-Qamar", "القمر", 55),
            QuranSurah(55, "Ar-Rahman", "الرحمن", 78),
            QuranSurah(56, "Al-Waqi'ah", "الواقعة", 96),
            QuranSurah(57, "Al-Hadid", "الحديد", 29),
            QuranSurah(58, "Al-Mujadila", "المجادلة", 22),
            QuranSurah(59, "Al-Hashr", "الحشر", 24),
            QuranSurah(60, "Al-Mumtahanah", "الممتحنة", 13),
            QuranSurah(61, "As-Saff", "الصف", 14),
            QuranSurah(62, "Al-Jumu'ah", "الجمعة", 11),
            QuranSurah(63, "Al-Munafiqun", "المنافقون", 11),
            QuranSurah(64, "At-Taghabun", "التغابن", 18),
            QuranSurah(65, "At-Talaq", "الطلاق", 12),
            QuranSurah(66, "At-Tahrim", "التحريم", 12),
            QuranSurah(67, "Al-Mulk", "الملك", 30),
            QuranSurah(68, "Al-Qalam", "القلم", 52),
            QuranSurah(69, "Al-Haqqah", "الحاقة", 52),
            QuranSurah(70, "Al-Ma'arij", "المعارج", 44),
            QuranSurah(71, "Nuh", "نوح", 28),
            QuranSurah(72, "Al-Jinn", "الجن", 28),
            QuranSurah(73, "Al-Muzzammil", "المزمل", 20),
            QuranSurah(74, "Al-Muddaththir", "المدثر", 56),
            QuranSurah(75, "Al-Qiyamah", "القيامة", 40),
            QuranSurah(76, "Al-Insan", " الانسان", 31),
            QuranSurah(77, "Al-Mursalat", "المرسلات", 50),
            QuranSurah(78, "An-Naba", "النبإ", 40),
            QuranSurah(79, "An-Nazi'at", "النازعات", 46),
            QuranSurah(80, "Abasa", "عبس", 42),
            QuranSurah(81, "At-Takwir", "التكوير", 29),
            QuranSurah(82, "Al-Infitar", "الإنفطار", 19),
            QuranSurah(83, "Al-Mutaffifin", "المطففين", 36),
            QuranSurah(84, "Al-Inshiqaq", "الإنشقاق", 25),
            QuranSurah(85, "Al-Buruj", "البروج", 22),
            QuranSurah(86, "At-Tariq", "الطارق", 17),
            QuranSurah(87, "Al-Ala", "الأعلى", 19),
            QuranSurah(88, "Al-Ghashiyah", "الغاشية", 26),
            QuranSurah(89, "Al-Fajr", "الفجر", 30),
            QuranSurah(90, "Al-Balad", "البلد", 20),
            QuranSurah(91, "Ash-Shams", "الشمس", 15),
            QuranSurah(92, "Al-Layl", "الليل", 21),
            QuranSurah(93, "Ad-Duhaa", "الضحى", 11),
            QuranSurah(94, "Ash-Sharh", "الشرح", 8),
            QuranSurah(95, "At-Tin", "التين", 8),
            QuranSurah(96, "Al-Alaq", "العلق", 19),
            QuranSurah(97, "Al-Qadr", "القدر", 5),
            QuranSurah(98, "Al-Bayyinah", "البينة", 8),
            QuranSurah(99, "Az-Zalzalah", "الزلزلة", 8),
            QuranSurah(100, "Al-Adiyat", "العاديات", 11),
            QuranSurah(101, "Al-Qari'ah", "القارعة", 11),
            QuranSurah(102, "At-Takathur", "التكاثر", 8),
            QuranSurah(103, "Al-Asr", "العصر", 3),
            QuranSurah(104, "Al-Humazah", "الهمزة", 9),
            QuranSurah(105, "Al-Fil", "الفيل", 5),
            QuranSurah(106, "Quraysh", "قريش", 4),
            QuranSurah(107, "Al-Ma'un", "الماعون", 7),
            QuranSurah(108, "Al-Kawthar", "الكوثر", 3),
            QuranSurah(109, "Al-Kafirun", "الكافرون", 6),
            QuranSurah(110, "An-Nasr", "النصر", 3),
            QuranSurah(111, "Al-Masad", "المسد", 5),
            QuranSurah(112, "Al-Ikhlas", "الإخلاص", 4),
            QuranSurah(113, "Al-Falaq", "الفلق", 5),
            QuranSurah(114, "An-Nas", "الناس", 6)
        )
    }
}